remote_theme: daviddarnes/alembic@main

exclude:
- README.md
- Gemfile
- Gemfile.lock

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

url: 'https://milesonerd.github.com'
baseurl: ''
title: 'Enzo Fuke'
description: 'This my personal Website'
permalink: pretty
logo: "https://avatars.githubusercontent.com/u/150525657?v=4"

paginate: 5
paginate_path: blog/page:num

navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

navigation_footer:
- title: Back to top
  url: "#top"

collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://www.unite.ai/wp-content/uploads/2022/04/AI-Python-Libraries-1000x600.png"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post 
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 
