const quotes = [
    { quote: "Aren't you a little short for a stormtrooper?", author: "Leia Organa" },
    { quote: "I am altering the deal, pray I do not alter it further.", author: "Darth Vader" },
    { quote: "No! I don't think he likes you at all... No, I don't like you either.", author: "C-3PO" },
    { quote: "I'm Luke Skywalker and I'm here to rescue you!", author: "Luke Skywalker" },
    { quote: "I recognized your foul stench when I was brought on board.", author: "Leia Organa" },
    { quote: "Why was she up there this whole time?!", author: "Okoye" },
    { quote: "I'm sorry. Earth is closed today. So pack it up, and get out of here.", author: "Tony Stark" },
    { quote: "Get over here!", author: "Scorpion" },
    { quote: "It's easy to forget what a sin is in the middle of a battlefield.", author: "Solid Snake" },
    { quote: "I used to be an adventurer like you, until I took an arrow to the knee.", author: "Town Guard" },
    { quote: "Live long and prosper.", author: "Spock" },
    { quote: "It's only a flesh wound.", author: "Knight of Knee" },
    { quote: "Alright everyone: Chill!", author: "Mr. Freeze" },
    { quote: "I volunteer as tribute!", author: "Katniss Everdeen" },
    { quote: "I'm a leaf on the wind.", author: "Wash" },
    { quote: "Leeloo Dallas Multipass.", author: "Leeloo" },
    { quote: "There is no spoon.", author: "Child" },
    { quote: "Witness me!", author: "Bloodbag" },
    { quote: "Do... or do not. There is no try.", author: "Yoda" },
    { quote: "The Force will be with you. Always.", author: "Obi-Wan Kenobi" },
    { quote: "Just one question... What if we miss?", author: "Cortana" },
    { quote: "Now, in front of you, I can finally die.", author: "Gray Fox" },
    { quote: "From the moment we're thrown into this world, we're fated to bring each other nothing but pain and misery.", author: "Psycho Mantis" },
    { quote: "You are a fool to come back here, stupid man.", author: "Sniper Wolf" },
    { quote: "I never felt truly alive unless I was staring death in the face.", author: "Solid Snake" },
    { quote: "Hey. Are you trying to bake me?", author: "Ken Marinaris" },
    { quote: "You must defeat Sheng Long to stand a chance!", author: "Ryu" },
    { quote: "I'm the strongest woman in the world!", author: "Chun Li" },
    { quote: "Cake, and grief counseling, will be available at the conclusion of the test.", author: "GLaDOS" },
    { quote: "Oh, hey! You're the lady from the test. Hi!", author: "Curiosity Sphere" },
    { quote: "We all make choices in life, but in the end our choices make us.", author: "Andrew Ryan" },
    { quote: "The right man in the wrong place can make all the difference in the world.", author: "G-Man" },
    { quote: "A man chooses; a slave obeys.", author: "Andrew Ryan" },
    { quote: "The President Has Been Kidnapped By Ninjas.", author: "Blade and Striker" },
    { quote: "With Great Power, Comes Great Responsibility", author: "Spiderman" },
    { quote: "It Dosen't Matter Who we are, what matters is our plan", author: "Bane" },
    { quote: "I Have seen the future Captain! There are no flags.", author: "Red Skull" },
    { quote: "This city is afraid of me, for I have seen it's true face.", author: "Rorschach" },
    { quote: "I don't like bullies, I don't care where they're from.", author: "Captain America" },
    { quote: "I'm sorry, Dave. I'm afraid I can't do that.", author: "HAL 9000" },
    { quote: "Conglaturation! You have completed a great game!", author: "Ghostbusters" },
    { quote: "People who live in glass houses get pretty good at ducking", author: "Manuel 'Manny' Calavera" },
    { quote: "...", author: "Gordon Freeman" },
    { quote: "Hulk SMASH!", author: "The Hulk" },
    { quote: "Hodor", author: "Hodor" },
    { quote: "That's my secret Captain, I'm always angry.", author: "Bruce Banner" },
    { quote: "If you cage the beast, the east will get angry.", author: "Wolverine" },
    { quote: "A day may come when the courage of men fails... but it is not THIS day.", author: "Aragorn" },
    { quote: "It is the quality of one's convictions that determines success, not the number of followers.", author: "Remus Lupin" },
    { quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "Sirius Black" },
    { quote: "The garbage will do.", author: "Rey" },
    { quote: "So who talks first, you talk first, I talk first?", author: "Poe Dameron" },
    { quote: "That's not how the Force works!", author: "Han Solo" },
    { quote: "I know.", author: "Han Solo" },
    { quote: "Let the Wookie win.", author: "C-3PO" },
    { quote: "What an incredible smell you've discovered.", author: "Han Solo" },
    { quote: "Who's the more foolish; the fool, or the fool who follows him?", author: "Obi-Wan Kenobi" },
    { quote: "There's an Ant-Man and a Spider-Man?", author: "Bruce Banner" },
    { quote: "Thank you, sweet rabbit.", author: "Thor" },
    { quote: "Oh, we're using our made-up names. I'm Spider-Man then.", author: "Peter Parker" },
    { quote: "Hey man, I'm Korg. We're gonna get out of here. Wanna come?", author: "Korg" },
    { quote: "What happens now determines what happens to the rest of the world.", author: "T'Challa" },
    { quote: "By Grabthar's hammer, by the suns of Worvan, you shall be avenged.", author: "Dr. Lazarus" },
    { quote: "I need your clothes, your boots and your motorcycle.", author: "T-800" },
    { quote: "Are you the keymaster?", author: "Dana" },
    { quote: "Where we're going, we don't need roads.", author: "Doc Brown" },
    { quote: "Help me, Obi-Wan Kenobi. You're my only hope.", author: "Leia Organa" },
    { quote: "You can't stop the change, any more than you can stop the suns from setting.", author: "Shmi Skywalker" },
    { quote: "Well, if droids could think, there'd be none of us here, would there?", author: "Obi-Wan Kenobi" },
    { quote: "I am Batman", author: "Batman" },
    { quote: "Traveling through hyperspace ain't like dusting crops, farm boy.", author: "Han Solo" },
    { quote: "This is your fault. I'm going to kill you. And all the cake is gone. You don't even care, do you?", author: "GLaDOS" },
    { quote: "Would you kindly...", author: "Atlas" },
    { quote: "Wakka wakka wakka.", author: "Pac-Man" },
    { quote: "RAZOR HAIL", author: "Marcus Fenix" },
    { quote: "You were almost a Jill sandwich!", author: "Barry Burton" },
    { quote: "The genius of the hole: No matter how long you spend climbing out, you can still fall back down in an instant.", author: "Max Payne" },
    { quote: "A winner is you", author: "Pro Wrestling" },
    { quote: "All your base are belong to us.", author: "CATS" },
    { quote: "Avengers Assemble!", author: "Captain America" },
];

function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

function updateQuote() {
    const { quote, author } = getRandomQuote();
    document.getElementById('random-quote').innerHTML = `&ldquo;${quote}&rdquo;`;
    document.getElementById('quote-author').innerHTML = `&mdash;${author}`;
}

document.addEventListener('DOMContentLoaded', () => {
    updateQuote();
    document.getElementById('another-quote').addEventListener('click', updateQuote);
});
