name: Update Copyright

on:
  schedule:
    - cron: "0 0 1 1 *" 

jobs:
  update-copyright:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Update Copyright in HTML files
        run: |
          find . -name "*.html" -exec sed -i 's/Copyright © 2024-2025/Copyright © 2024-2026/g' {} +
          git config --global user.name "Enzo Fuke"
          git config --global user.email "150525657+MilesONerd@users.noreply.github.com"
          git add .
          git commit -m "Updating Copyright to 2026"
          git push
